/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_landcell_free: (a: number, b: number) => void;
export const __wbg_get_landcell_land_level: (a: number) => number;
export const __wbg_set_landcell_land_level: (a: number, b: number) => void;
export const __wbg_get_landcell_water_level: (a: number) => number;
export const __wbg_set_landcell_water_level: (a: number, b: number) => void;
export const __wbg_landscape_free: (a: number, b: number) => void;
export const landscape_tick: (a: number) => void;
export const landscape_reset: (a: number) => void;
export const landscape_new_bowl: () => number;
export const landscape_new_from_dem: (a: number, b: number, c: number, d: number) => number;
export const landscape_width: (a: number) => number;
export const landscape_height: (a: number) => number;
export const landscape_cells: (a: number) => number;
export const landscape_set_water: (a: number, b: number, c: number, d: number) => void;
export const landscape_make_stream: (a: number, b: number, c: number) => void;
export const __wbg_universe_free: (a: number, b: number) => void;
export const universe_new: () => number;
export const universe_new_mod7: () => number;
export const universe_new_random: () => number;
export const universe_tick: (a: number) => void;
export const universe_render: (a: number) => [number, number];
export const universe_width: (a: number) => number;
export const universe_height: (a: number) => number;
export const universe_cells: (a: number) => number;
export const universe_set_width: (a: number, b: number) => void;
export const universe_set_height: (a: number, b: number) => void;
export const universe_toggle_cell: (a: number, b: number, c: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_3: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
